"""FROZEN data contract — Setup / Geometry Contract v2.1 (+ v2.2 naming revision).

This module is transcribed VERBATIM from the Setup/Geometry Contract v2.1
(sections 1-6): the same field names, types, enum members, ``known_at_bar``
annotations, and Protocol signatures. It is the fixed point every other module
imports from and conforms to.

DO NOT rename, retype, collapse, or "improve" any field. The contract's single
controlled-revision slot is spent (Contract section 11.1 / Implementation Plan
convention 1). If a field appears wrong or insufficient, STOP and escalate to
the human; do not edit this file.

Structural notes preserved from the contract:
  * ``TerminationReason`` has exactly two members: ``INVALIDATED`` and
    ``TIMEOUT``. Fills do NOT terminate the lifecycle (v2.1).
  * The geometry stream spans ``entry_eligible_bar`` through
    ``terminated_at_bar`` inclusive and is never truncated at a fill.
  * Materialization is Option B: raw bars persist; the ``SetupUpdate`` stream
    and ``SetupLifecycle`` are the return shape of the on-demand materializer.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Protocol, Sequence


# =============================================================================
# 1. Conventions and primitives
# =============================================================================

# 1.1 Bars and bar indices
# `bar_index` is the canonical time reference; timestamps are informational.
# Bar `t`'s OHLC is known only at the CLOSE of bar `t`.

@dataclass(frozen=True)
class Bar:
    bar_index: int
    timestamp: str        # ISO 8601, UTC; informational only
    open: float
    high: float
    low: float
    close: float
    volume: float | None = None


# 1.2 Causal primitives

@dataclass(frozen=True)
class CausalPrice:
    price: float
    defining_bar: int     # bar index that establishes this level
    known_at_bar: int     # bar index at whose CLOSE this becomes knowable
    # INVARIANT: known_at_bar >= defining_bar
    # Pivot-type levels: known_at_bar == defining_bar + N (strictly greater)


@dataclass(frozen=True)
class ProjectedLevel:
    price: float
    computed_at_bar: int  # = t; known at the close of t
    active_at_bar: int    # the future bar the resting order is live for
    # INVARIANT: active_at_bar > computed_at_bar
    # Default projection horizon: active_at_bar == computed_at_bar + 1
    # (projection-horizon choice is a VALUE, resolved in the detector spec)


# 1.3 Enums

class Direction(Enum):
    LONG = "long"
    SHORT = "short"


class TrancheType(Enum):
    MEAN_REVERSION = "mr"
    WITH_TREND = "wt"


class OrderType(Enum):
    LIMIT = "limit"            # MR entries
    STOP_LIMIT = "stop_limit"  # with-trend entries


class TriggerType(Enum):
    INSIDE_BAR = "inside_bar"
    ID_NR7 = "id_nr7"
    ID_NR5 = "id_nr5"
    PIVOT = "pivot"
    LTF_PIVOT = "ltf_pivot"
    FAILURE_TEST = "failure_test"
    OTHER = "other"


class GrimesVariant(Enum):      # FEATURE, never a filter (permissive-first)
    SIMPLE = "simple"
    ANTI_SNAP = "anti_snap"
    NESTED = "nested"
    COMPLEX = "complex"
    UNCLASSIFIED = "unclassified"


class FillModel(Enum):
    TOUCH = "touch"
    TRADE_THROUGH = "trade_through"


class TrancheComposition(Enum):
    NONE = "none"
    MR_ONLY = "mr_only"
    WT_ONLY = "wt_only"
    MIXED = "mixed"


class TerminationReason(Enum):
    # v2.1: fills are NOT terminators. A lifecycle ends only when the
    # entry-opportunity window closes. Fills are recorded on SimulatedEntry.
    INVALIDATED = "invalidated"  # 2/3-retracement floor breached OR high >= impulse_end (thesis dead)
    TIMEOUT = "timeout"          # max_pending_window exhausted with the window still open


# 1.4 Instrument metadata

@dataclass(frozen=True)
class InstrumentMeta:
    symbol: str
    tick_size: float
    point_value: float
    default_slippage_ticks: float
    is_spot_fx: bool = False


# =============================================================================
# 2. Stage 1 — the setup lifecycle
# =============================================================================

# 2.1 Static opening record

@dataclass(frozen=True)
class StaticFeatures:
    """Detection-time qualifiers. EMITTED, NEVER FILTERED (permissive-first).
    Time-varying features live on SetupUpdate, not here."""
    grimes_variant: GrimesVariant
    pullback_count_in_trend: int | None    # 1,2,3,...; None if trend undefined
    weekly_agreement_at_detection: float | None
    vol_ratio_at_detection: float | None
    wick_indecision_at_detection: float | None


@dataclass(frozen=True)
class DetectedSetupOpening:
    # identity / provenance
    setup_id: str                 # stable hash of (symbol, timeframe, detection_bar, geometry)
    symbol: str
    timeframe: str
    detector_version: str
    param_hash: str
    generated_at: str

    # classification / timing
    direction: Direction
    detection_bar: int
    entry_eligible_bar: int       # == detection_bar + 1; first session orders are live
    pullback_start_bar: int       # anchor for maturity_barcount

    # static geometry (impulse is fixed once known)
    impulse_origin: CausalPrice   # invalidation anchor
    impulse_end: CausalPrice      # impulse extreme / pullback start
    atr_at_detection: float
    atr_period: int

    # static derived level (held ONCE here; referenced by updates, not repeated)
    # LONG: impulse_end.price - (2/3)*(impulse_end.price - impulse_origin.price); mirror for SHORT
    retracement_floor: float

    features: StaticFeatures

    # v2.1 — Option B materialization substrate.
    # The raw bars the constructor needs to re-derive the geometry stream on demand:
    # everything from (entry_eligible_bar - pre_anchor_lookback) through
    # (entry_eligible_bar - 1). Sized to cover the maximum plausible estimator-C
    # window + ATR period + warm-up (a VALUE, section 10). Causally clean: every bar here
    # precedes entry_eligible_bar, so it is fully known at detection.
    # Forward bars (entry_eligible_bar onward) live on ForwardPath (section 4); the two
    # together form the complete uncensored bar substrate for this setup.
    pre_anchor_bars: tuple[Bar, ...]
    pre_anchor_lookback: int          # == len(pre_anchor_bars); count of pre-anchor bars stored

    # forward-compatibility hook (nullable; unused by current version) — see 11.2
    correlation_cluster: str | None = None


# 2.2 Per-bar geometry stream (materialized on demand)

@dataclass(frozen=True)
class SetupUpdate:
    setup_id: str                 # foreign key to the opening record
    bar_index: int                # = t; all fields known at close of t

    # mechanical stream
    running_extreme: CausalPrice      # L(t): running literal extreme on the countertrend side of the
                                       # pullback — running-min low for LONG, running-max high for
                                       # SHORT (mirror); monotonic; never repaints
    mean_true_range_pullback: float   # V(t): mean TRUE range of pullback bars so far
    countertrend_boundary_next: ProjectedLevel   # estimator C, projected to t+1. The fitted (not
                                       # literal) countertrend boundary: a robust fit to the pullback's
                                       # lows for LONG, highs for SHORT (mirror) — the boundary the MR
                                       # limit rests against. Distinct from running_extreme (Detector
                                       # Spec section 8.1/8.2).
    mr_trigger_next: ProjectedLevel          # = max(countertrend_boundary_next - alpha(m(t))*V(t),
                                             #        opening.retracement_floor)  [LONG; mirror SHORT]
    fit_dispersion: float | None      # estimator C residual dispersion / jitter; None during warm-up

    # maturity features — BOTH emitted (characterization); live offset selects one
    maturity_barcount: int            # bars since opening.pullback_start_bar
    maturity_retracement: float       # (impulse_end - L(t)) / ((2/3)*(impulse_end - impulse_origin)) [LONG]

    # candidate stop-volatility unit — nullable; may be dropped if RQ1 finds ATR/V dominate
    with_trend_boundary_next: ProjectedLevel | None  # the far-side (with-trend) boundary: pullback
                                       # highs for LONG, pullback lows for SHORT (mirror) — the
                                       # opposite extrema from countertrend_boundary_next
    d_struct: float | None            # channel height if with_trend_boundary_next retained

    atr: float                        # competing stop-volatility unit


# 2.3 Lifecycle container (holds terminal outcome)

@dataclass(frozen=True)
class SetupLifecycle:
    opening: DetectedSetupOpening
    updates: tuple[SetupUpdate, ...]      # ordered by bar_index, ascending; materialized on demand
    terminated_at_bar: int
    termination_reason: TerminationReason  # INVALIDATED or TIMEOUT only (v2.1)
    # INVARIANT: updates[0].bar_index == opening.entry_eligible_bar
    # INVARIANT: updates[-1].bar_index == terminated_at_bar
    #            (v2.1: stream runs to window close, not to first fill; equality, not <=)
    # INVARIANT: updates are contiguous by bar_index with no gaps
    # INVARIANT: every update.setup_id == opening.setup_id
    # INVARIANT: termination_reason in {INVALIDATED, TIMEOUT}


@dataclass(frozen=True)
class SetupTerminalOutcome:
    """The persisted terminal slice (section 2.3). May be inlined; kept as its own
    small record so the materializer can reconstruct the full SetupLifecycle."""
    setup_id: str
    terminated_at_bar: int
    termination_reason: TerminationReason


# =============================================================================
# 3. Stage 2 — entry simulation and fills
# =============================================================================

@dataclass(frozen=True)
class EntryConfig:
    entry_config_id: str
    fill_model: FillModel
    slippage_ticks: float
    second_mr_level_rule: str     # rule id for the 2nd MR entry (provisional placeholder overridden here)
    require_trade_through_for_limit: bool = True


@dataclass(frozen=True)
class FillTimeGeometry:
    mr_trigger_at_fill: float
    running_extreme_at_fill: float
    mean_true_range_at_fill: float
    atr_at_fill: float
    d_struct_at_fill: float | None      # nullable, per section 2.2
    entry_to_origin_at_fill: float


@dataclass(frozen=True)
class TrancheFill:
    tranche_id: str
    tranche_type: TrancheType
    filled: bool
    fill_bar: int | None                  # >= entry_eligible_bar; None if unfilled
    requested_price: float
    fill_price: float | None
    slippage_applied: float
    filled_on_trade_through: bool | None  # MR daily close-based proxy; None if WT/unfilled
    fill_time_geometry: FillTimeGeometry | None  # None if unfilled


@dataclass(frozen=True)
class SimulatedEntry:
    setup_id: str
    entry_config_id: str
    tranche_fills: tuple[TrancheFill, ...]
    composition: TrancheComposition     # derived from which tranches filled


# =============================================================================
# 4. Stage 3 — ForwardPath (uncensored)
# =============================================================================

@dataclass(frozen=True)
class ForwardPathBar:
    bar_offset: int          # 0 == anchor bar
    bar_index: int
    high: float
    low: float
    close: float
    intraday_high: float | None = None   # None in the current daily-only version
    intraday_low: float | None = None


@dataclass(frozen=True)
class ForwardPath:
    setup_id: str
    anchor_bar: int          # == entry_eligible_bar
    max_pending_window: int  # bounded by TIMEOUT; makes length deterministic
    horizon_H: int           # provisional 15-20 trading days + fill-latency buffer (VALUE; pending sign-off)
    total_length: int        # == max_pending_window + horizon_H
    bars: tuple[ForwardPathBar, ...]
    truncated_by_data_end: bool
    # INVARIANT: len(bars) == total_length unless truncated_by_data_end
    # INVARIANT: no stop/target/exit logic applied during construction


# =============================================================================
# 6. Interfaces
# =============================================================================

# 6.1 BoundaryConstructor and the geometry materializer (the seam; structural)

class MaturityFn(Protocol):
    def __call__(self, opening: DetectedSetupOpening,
                 bars_up_to_t: Sequence[Bar], t: int) -> float: ...


class BoundaryConstructor(Protocol):
    def compute_update(self, opening: DetectedSetupOpening,
                       bars_up_to_t: Sequence[Bar], t: int,
                       maturity_fn: MaturityFn) -> SetupUpdate:
        """Return the causal SetupUpdate for bar t using ONLY bars <= t.
        Must populate fit_dispersion (or None during warm-up) and BOTH
        maturity features regardless of which one maturity_fn selects for alpha."""
        ...


class GeometryMaterializer(Protocol):
    def materialize(self, opening: DetectedSetupOpening,
                    forward_path: ForwardPath,
                    terminated_at_bar: int,
                    termination_reason: TerminationReason,
                    constructor: BoundaryConstructor,
                    maturity_fn: MaturityFn) -> SetupLifecycle:
        """Rebuild the full SetupLifecycle from persisted bars.
        For each bar t in [opening.entry_eligible_bar, terminated_at_bar],
        assemble bars_up_to_t from (opening.pre_anchor_bars + forward_path.bars)
        restricted to bar_index <= t, and call constructor.compute_update(...).
        MUST NOT pass any bar with bar_index > t (no look-ahead). The returned
        stream is contiguous and byte-identical to what a generation-time stream
        would have contained — this equivalence is enforced by section 8.1."""
        ...


# 6.2 Input adapter

class BarSeriesProvider(Protocol):
    def get_bars(self, symbol: str, timeframe: str,
                 start_index: int | None, end_index: int | None) -> Sequence[Bar]:
        """Ascending by bar_index, inclusive of bounds.
        MUST NOT return bars beyond end_index (no-look-ahead at the data boundary)."""
        ...
